name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run linter
      run: npm run lint
    
    - name: Start test server and run tests
      run: |
        # Start the test server in the background
        cd public
        python3 -m http.server 3000 &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Run the tests
        cd ..
        npm test
        
        # Clean up server
        kill $SERVER_PID
      shell: bash
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          cypress/screenshots/
          cypress/videos/
          cypress/downloads/

  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Check build output
      run: |
        if [ ! -f "dist/index.js" ]; then
          echo "Build failed: dist/index.js not found"
          exit 1
        fi
        if [ ! -f "dist/index.d.ts" ]; then
          echo "Build failed: dist/index.d.ts not found"
          exit 1
        fi
        echo "Build successful - all files present"
    
    - name: Verify package.json
      run: |
        npm pack --dry-run
        echo "Package verification successful"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
